### PR TITLE
Added images and fix for fullname extraction

### PR DESCRIPTION
**Pull request by leejsinclair**

### CODE REVIEW

**Comment by hackergrrl** [comment]
Thanks! :tada: 

Would you like to be added as a collaborator?

**Comment by hackergrrl** [comment]
Published in 1.0.4

**Comment by leejsinclair** [comment]
Thanks.

I'm thinking of adding in some metadata extraction like mentions, hashtags and links.  Are you interested in these features? If so, I'd be happy to join as a collaborator

**Comment by hackergrrl** [comment]
@leejsinclair I'm not really building on or using this module any more, so anything you'd like is good by me :)

**Pull request merged**
